name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  formatted:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: latest
      - run: gleam format --check src test

  test-erlang:
    strategy:
      matrix:
        otp-version: ["26", "27"]
        gleam-version: ["1.4", "1.5", "1.6", "1.7", "1.8", "1.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp-version }}
          gleam-version: ${{ matrix.gleam-version }}
      - run: gleam deps download
      - run: gleam test --target erlang

  test-node:
    strategy:
      matrix:
        node-version: ["22", "23"]
        gleam-version: ["1.4", "1.5", "1.6", "1.7", "1.8", "1.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          gleam-version: ${{ matrix.gleam-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: gleam deps download
      - run: gleam test --target javascript --runtime node

  test-deno:
    strategy:
      matrix:
        deno-version: ["v1.x", "v2.x"]
        gleam-version: ["1.4", "1.5", "1.6", "1.7", "1.8", "1.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          gleam-version: ${{ matrix.gleam-version }}
      - uses: denoland/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - run: gleam deps download
      - run: gleam test --target javascript --runtime deno

  test-bun:
    strategy:
      matrix:
        bun-version: ["latest"]
        gleam-version: ["1.4", "1.5", "1.6", "1.7", "1.8", "1.9"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 27
          gleam-version: ${{ matrix.gleam-version }}
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}
      - run: gleam deps download
      - run: gleam test --target javascript --runtime bun
